import 'package:dio/dio.dart';
import 'package:flutter/material.dart';

import 'package:http/http.dart' as http;

import 'package:untitled7/model_confwert.dart';

// String url = "https://hishamalalimi.com/hafiz_web/api/v1/get-categories-stores";

Future<List<Data>> getData1() async {
  final response = await Dio()
      .get("https://hishamalalimi.com/hafiz_web/api/v1/get-categories-stores");

  if (response.statusCode == 200) {
    print(response);
    return List<Data>.from(
        (response.data["data"] as List).map((e) => Data.fromJson(e)));
    //  print(Catger_models);
  } else {
    throw Exception(DiagnosticsNode.message("iuyiyiuyiy"));

    // Autogenerated.fromJson(response.data)
  }
  //print(Catger_models);
}
