
class Autogenerated {
  bool? status;
  String? errNum;
  String? msg;
  List<Data>? data;

  Autogenerated({this.status, this.errNum, this.msg, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    errNum = json['errNum'];
    msg = json['msg'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['errNum'] = this.errNum;
    data['msg'] = this.msg;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}
class Data {
  int? id;
  String? name;
  String? sorting;
  String? description;
  String? image;
  String? parentId;
  List<SubCategories>? subCategories;

  Data(
      {this.id,
        this.name,
        this.sorting,
        this.description,
        this.image,
        this.parentId,
        this.subCategories});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    sorting = json['sorting'];
    description = json['description'];
    image = json['image'];
    parentId = json['parent_id'];
    if (json['sub_categories'] != null) {
      subCategories = <SubCategories>[];
      json['sub_categories'].forEach((v) {
        subCategories!.add(new SubCategories.fromJson(v));
      });
    }
  }



  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['sorting'] = this.sorting;
    data['description'] = this.description;
    data['image'] = this.image;
    data['parent_id'] = this.parentId;
    if (this.subCategories != null) {
      data['sub_categories'] =
          this.subCategories!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class SubCategories {
  int? id;
  String? name;
  String? sorting;
  String? description;
  String? image;
  String? parentId;
  List<Null>? subCategories;

  SubCategories(
      {this.id,
        this.name,
        this.sorting,
        this.description,
        this.image,
        this.parentId,
        this.subCategories});

  SubCategories.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    sorting = json['sorting'];
    description = json['description'];
    image = json['image'];
    parentId = json['parent_id'];
    if (json['sub_categories'] != null) {
      subCategories = <Null>[];
      json['sub_categories'].forEach((v) {
        subCategories!.add;
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['sorting'] = this.sorting;
    data['description'] = this.description;
    data['image'] = this.image;
    data['parent_id'] = this.parentId;
    if (this.subCategories != null) {
      data['sub_categories'] =
          this.subCategories!.map((v) => toJson()).toList();
    }
    return data;
  }
}







